vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        product_categories:
            uri_prefix: /images/product_categories
            upload_destination: '%kernel.project_dir%/public/images/product_categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
