services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: api_php
        working_dir: /var/www/html
        environment:
            APP_ENV: ${APP_ENV:-dev}
            APP_SECRET: ${APP_SECRET}
            DATABASE_URL: ${DATABASE_URL}
        volumes:
            - ./:/var/www/html
        depends_on:
            db:
                condition: service_healthy

    web:
        image: nginx:1.27-alpine
        container_name: api_web
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: api_db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    db_data:


